/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YouthRouteImport } from './routes/youth'
import { Route as TempleRouteImport } from './routes/temple'
import { Route as SocialMediaRouteImport } from './routes/social-media'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as PrahladaBadiRouteImport } from './routes/prahlada-badi'
import { Route as HarinamaRouteImport } from './routes/harinama'
import { Route as GoshalaRouteImport } from './routes/goshala'
import { Route as GitaCourseRouteImport } from './routes/gita-course'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FestivalsRouteImport } from './routes/festivals'
import { Route as EkadashiRouteImport } from './routes/ekadashi'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TempleIndexRouteImport } from './routes/temple.index'
import { Route as DonateIndexRouteImport } from './routes/donate.index'
import { Route as TempleSundayRouteImport } from './routes/temple.sunday'
import { Route as PaySlugRouteImport } from './routes/pay.$slug'
import { Route as FestivalSlugRouteImport } from './routes/festival.$slug'
import { Route as DonateSlugRouteImport } from './routes/donate.$slug'
import { Route as AboutMissionRouteImport } from './routes/about.mission'
import { Route as AboutKurnoolRouteImport } from './routes/about.kurnool'
import { Route as AboutIskconRouteImport } from './routes/about.iskcon'
import { Route as AboutFounderRouteImport } from './routes/about.founder'

const YouthRoute = YouthRouteImport.update({
  id: '/youth',
  path: '/youth',
  getParentRoute: () => rootRouteImport,
} as any)
const TempleRoute = TempleRouteImport.update({
  id: '/temple',
  path: '/temple',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialMediaRoute = SocialMediaRouteImport.update({
  id: '/social-media',
  path: '/social-media',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const PrahladaBadiRoute = PrahladaBadiRouteImport.update({
  id: '/prahlada-badi',
  path: '/prahlada-badi',
  getParentRoute: () => rootRouteImport,
} as any)
const HarinamaRoute = HarinamaRouteImport.update({
  id: '/harinama',
  path: '/harinama',
  getParentRoute: () => rootRouteImport,
} as any)
const GoshalaRoute = GoshalaRouteImport.update({
  id: '/goshala',
  path: '/goshala',
  getParentRoute: () => rootRouteImport,
} as any)
const GitaCourseRoute = GitaCourseRouteImport.update({
  id: '/gita-course',
  path: '/gita-course',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalsRoute = FestivalsRouteImport.update({
  id: '/festivals',
  path: '/festivals',
  getParentRoute: () => rootRouteImport,
} as any)
const EkadashiRoute = EkadashiRouteImport.update({
  id: '/ekadashi',
  path: '/ekadashi',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TempleIndexRoute = TempleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TempleRoute,
} as any)
const DonateIndexRoute = DonateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DonateRoute,
} as any)
const TempleSundayRoute = TempleSundayRouteImport.update({
  id: '/sunday',
  path: '/sunday',
  getParentRoute: () => TempleRoute,
} as any)
const PaySlugRoute = PaySlugRouteImport.update({
  id: '/pay/$slug',
  path: '/pay/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalSlugRoute = FestivalSlugRouteImport.update({
  id: '/festival/$slug',
  path: '/festival/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateSlugRoute = DonateSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DonateRoute,
} as any)
const AboutMissionRoute = AboutMissionRouteImport.update({
  id: '/about/mission',
  path: '/about/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutKurnoolRoute = AboutKurnoolRouteImport.update({
  id: '/about/kurnool',
  path: '/about/kurnool',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIskconRoute = AboutIskconRouteImport.update({
  id: '/about/iskcon',
  path: '/about/iskcon',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutFounderRoute = AboutFounderRouteImport.update({
  id: '/about/founder',
  path: '/about/founder',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/connect': typeof ConnectRoute
  '/courses': typeof CoursesRoute
  '/donate': typeof DonateRouteWithChildren
  '/ekadashi': typeof EkadashiRoute
  '/festivals': typeof FestivalsRoute
  '/gallery': typeof GalleryRoute
  '/gita-course': typeof GitaCourseRoute
  '/goshala': typeof GoshalaRoute
  '/harinama': typeof HarinamaRoute
  '/prahlada-badi': typeof PrahladaBadiRoute
  '/shop': typeof ShopRoute
  '/social-media': typeof SocialMediaRoute
  '/temple': typeof TempleRouteWithChildren
  '/youth': typeof YouthRoute
  '/about/founder': typeof AboutFounderRoute
  '/about/iskcon': typeof AboutIskconRoute
  '/about/kurnool': typeof AboutKurnoolRoute
  '/about/mission': typeof AboutMissionRoute
  '/donate/$slug': typeof DonateSlugRoute
  '/festival/$slug': typeof FestivalSlugRoute
  '/pay/$slug': typeof PaySlugRoute
  '/temple/sunday': typeof TempleSundayRoute
  '/donate/': typeof DonateIndexRoute
  '/temple/': typeof TempleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/connect': typeof ConnectRoute
  '/courses': typeof CoursesRoute
  '/ekadashi': typeof EkadashiRoute
  '/festivals': typeof FestivalsRoute
  '/gallery': typeof GalleryRoute
  '/gita-course': typeof GitaCourseRoute
  '/goshala': typeof GoshalaRoute
  '/harinama': typeof HarinamaRoute
  '/prahlada-badi': typeof PrahladaBadiRoute
  '/shop': typeof ShopRoute
  '/social-media': typeof SocialMediaRoute
  '/youth': typeof YouthRoute
  '/about/founder': typeof AboutFounderRoute
  '/about/iskcon': typeof AboutIskconRoute
  '/about/kurnool': typeof AboutKurnoolRoute
  '/about/mission': typeof AboutMissionRoute
  '/donate/$slug': typeof DonateSlugRoute
  '/festival/$slug': typeof FestivalSlugRoute
  '/pay/$slug': typeof PaySlugRoute
  '/temple/sunday': typeof TempleSundayRoute
  '/donate': typeof DonateIndexRoute
  '/temple': typeof TempleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/connect': typeof ConnectRoute
  '/courses': typeof CoursesRoute
  '/donate': typeof DonateRouteWithChildren
  '/ekadashi': typeof EkadashiRoute
  '/festivals': typeof FestivalsRoute
  '/gallery': typeof GalleryRoute
  '/gita-course': typeof GitaCourseRoute
  '/goshala': typeof GoshalaRoute
  '/harinama': typeof HarinamaRoute
  '/prahlada-badi': typeof PrahladaBadiRoute
  '/shop': typeof ShopRoute
  '/social-media': typeof SocialMediaRoute
  '/temple': typeof TempleRouteWithChildren
  '/youth': typeof YouthRoute
  '/about/founder': typeof AboutFounderRoute
  '/about/iskcon': typeof AboutIskconRoute
  '/about/kurnool': typeof AboutKurnoolRoute
  '/about/mission': typeof AboutMissionRoute
  '/donate/$slug': typeof DonateSlugRoute
  '/festival/$slug': typeof FestivalSlugRoute
  '/pay/$slug': typeof PaySlugRoute
  '/temple/sunday': typeof TempleSundayRoute
  '/donate/': typeof DonateIndexRoute
  '/temple/': typeof TempleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/connect'
    | '/courses'
    | '/donate'
    | '/ekadashi'
    | '/festivals'
    | '/gallery'
    | '/gita-course'
    | '/goshala'
    | '/harinama'
    | '/prahlada-badi'
    | '/shop'
    | '/social-media'
    | '/temple'
    | '/youth'
    | '/about/founder'
    | '/about/iskcon'
    | '/about/kurnool'
    | '/about/mission'
    | '/donate/$slug'
    | '/festival/$slug'
    | '/pay/$slug'
    | '/temple/sunday'
    | '/donate/'
    | '/temple/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/connect'
    | '/courses'
    | '/ekadashi'
    | '/festivals'
    | '/gallery'
    | '/gita-course'
    | '/goshala'
    | '/harinama'
    | '/prahlada-badi'
    | '/shop'
    | '/social-media'
    | '/youth'
    | '/about/founder'
    | '/about/iskcon'
    | '/about/kurnool'
    | '/about/mission'
    | '/donate/$slug'
    | '/festival/$slug'
    | '/pay/$slug'
    | '/temple/sunday'
    | '/donate'
    | '/temple'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/connect'
    | '/courses'
    | '/donate'
    | '/ekadashi'
    | '/festivals'
    | '/gallery'
    | '/gita-course'
    | '/goshala'
    | '/harinama'
    | '/prahlada-badi'
    | '/shop'
    | '/social-media'
    | '/temple'
    | '/youth'
    | '/about/founder'
    | '/about/iskcon'
    | '/about/kurnool'
    | '/about/mission'
    | '/donate/$slug'
    | '/festival/$slug'
    | '/pay/$slug'
    | '/temple/sunday'
    | '/donate/'
    | '/temple/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ConnectRoute: typeof ConnectRoute
  CoursesRoute: typeof CoursesRoute
  DonateRoute: typeof DonateRouteWithChildren
  EkadashiRoute: typeof EkadashiRoute
  FestivalsRoute: typeof FestivalsRoute
  GalleryRoute: typeof GalleryRoute
  GitaCourseRoute: typeof GitaCourseRoute
  GoshalaRoute: typeof GoshalaRoute
  HarinamaRoute: typeof HarinamaRoute
  PrahladaBadiRoute: typeof PrahladaBadiRoute
  ShopRoute: typeof ShopRoute
  SocialMediaRoute: typeof SocialMediaRoute
  TempleRoute: typeof TempleRouteWithChildren
  YouthRoute: typeof YouthRoute
  AboutFounderRoute: typeof AboutFounderRoute
  AboutIskconRoute: typeof AboutIskconRoute
  AboutKurnoolRoute: typeof AboutKurnoolRoute
  AboutMissionRoute: typeof AboutMissionRoute
  FestivalSlugRoute: typeof FestivalSlugRoute
  PaySlugRoute: typeof PaySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youth': {
      id: '/youth'
      path: '/youth'
      fullPath: '/youth'
      preLoaderRoute: typeof YouthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temple': {
      id: '/temple'
      path: '/temple'
      fullPath: '/temple'
      preLoaderRoute: typeof TempleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-media': {
      id: '/social-media'
      path: '/social-media'
      fullPath: '/social-media'
      preLoaderRoute: typeof SocialMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prahlada-badi': {
      id: '/prahlada-badi'
      path: '/prahlada-badi'
      fullPath: '/prahlada-badi'
      preLoaderRoute: typeof PrahladaBadiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harinama': {
      id: '/harinama'
      path: '/harinama'
      fullPath: '/harinama'
      preLoaderRoute: typeof HarinamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goshala': {
      id: '/goshala'
      path: '/goshala'
      fullPath: '/goshala'
      preLoaderRoute: typeof GoshalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gita-course': {
      id: '/gita-course'
      path: '/gita-course'
      fullPath: '/gita-course'
      preLoaderRoute: typeof GitaCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festivals': {
      id: '/festivals'
      path: '/festivals'
      fullPath: '/festivals'
      preLoaderRoute: typeof FestivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ekadashi': {
      id: '/ekadashi'
      path: '/ekadashi'
      fullPath: '/ekadashi'
      preLoaderRoute: typeof EkadashiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temple/': {
      id: '/temple/'
      path: '/'
      fullPath: '/temple/'
      preLoaderRoute: typeof TempleIndexRouteImport
      parentRoute: typeof TempleRoute
    }
    '/donate/': {
      id: '/donate/'
      path: '/'
      fullPath: '/donate/'
      preLoaderRoute: typeof DonateIndexRouteImport
      parentRoute: typeof DonateRoute
    }
    '/temple/sunday': {
      id: '/temple/sunday'
      path: '/sunday'
      fullPath: '/temple/sunday'
      preLoaderRoute: typeof TempleSundayRouteImport
      parentRoute: typeof TempleRoute
    }
    '/pay/$slug': {
      id: '/pay/$slug'
      path: '/pay/$slug'
      fullPath: '/pay/$slug'
      preLoaderRoute: typeof PaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festival/$slug': {
      id: '/festival/$slug'
      path: '/festival/$slug'
      fullPath: '/festival/$slug'
      preLoaderRoute: typeof FestivalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/$slug': {
      id: '/donate/$slug'
      path: '/$slug'
      fullPath: '/donate/$slug'
      preLoaderRoute: typeof DonateSlugRouteImport
      parentRoute: typeof DonateRoute
    }
    '/about/mission': {
      id: '/about/mission'
      path: '/about/mission'
      fullPath: '/about/mission'
      preLoaderRoute: typeof AboutMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/kurnool': {
      id: '/about/kurnool'
      path: '/about/kurnool'
      fullPath: '/about/kurnool'
      preLoaderRoute: typeof AboutKurnoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/iskcon': {
      id: '/about/iskcon'
      path: '/about/iskcon'
      fullPath: '/about/iskcon'
      preLoaderRoute: typeof AboutIskconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/founder': {
      id: '/about/founder'
      path: '/about/founder'
      fullPath: '/about/founder'
      preLoaderRoute: typeof AboutFounderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DonateRouteChildren {
  DonateSlugRoute: typeof DonateSlugRoute
  DonateIndexRoute: typeof DonateIndexRoute
}

const DonateRouteChildren: DonateRouteChildren = {
  DonateSlugRoute: DonateSlugRoute,
  DonateIndexRoute: DonateIndexRoute,
}

const DonateRouteWithChildren =
  DonateRoute._addFileChildren(DonateRouteChildren)

interface TempleRouteChildren {
  TempleSundayRoute: typeof TempleSundayRoute
  TempleIndexRoute: typeof TempleIndexRoute
}

const TempleRouteChildren: TempleRouteChildren = {
  TempleSundayRoute: TempleSundayRoute,
  TempleIndexRoute: TempleIndexRoute,
}

const TempleRouteWithChildren =
  TempleRoute._addFileChildren(TempleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ConnectRoute: ConnectRoute,
  CoursesRoute: CoursesRoute,
  DonateRoute: DonateRouteWithChildren,
  EkadashiRoute: EkadashiRoute,
  FestivalsRoute: FestivalsRoute,
  GalleryRoute: GalleryRoute,
  GitaCourseRoute: GitaCourseRoute,
  GoshalaRoute: GoshalaRoute,
  HarinamaRoute: HarinamaRoute,
  PrahladaBadiRoute: PrahladaBadiRoute,
  ShopRoute: ShopRoute,
  SocialMediaRoute: SocialMediaRoute,
  TempleRoute: TempleRouteWithChildren,
  YouthRoute: YouthRoute,
  AboutFounderRoute: AboutFounderRoute,
  AboutIskconRoute: AboutIskconRoute,
  AboutKurnoolRoute: AboutKurnoolRoute,
  AboutMissionRoute: AboutMissionRoute,
  FestivalSlugRoute: FestivalSlugRoute,
  PaySlugRoute: PaySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
