/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YouthRouteImport } from './routes/youth'
import { Route as TempleRouteImport } from './routes/temple'
import { Route as GoshalaRouteImport } from './routes/goshala'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FestivalSlugRouteImport } from './routes/festival.$slug'
import { Route as AboutMissionRouteImport } from './routes/about.mission'
import { Route as AboutKurnoolRouteImport } from './routes/about.kurnool'
import { Route as AboutIskconRouteImport } from './routes/about.iskcon'
import { Route as AboutFounderRouteImport } from './routes/about.founder'

const YouthRoute = YouthRouteImport.update({
  id: '/youth',
  path: '/youth',
  getParentRoute: () => rootRouteImport,
} as any)
const TempleRoute = TempleRouteImport.update({
  id: '/temple',
  path: '/temple',
  getParentRoute: () => rootRouteImport,
} as any)
const GoshalaRoute = GoshalaRouteImport.update({
  id: '/goshala',
  path: '/goshala',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalSlugRoute = FestivalSlugRouteImport.update({
  id: '/festival/$slug',
  path: '/festival/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMissionRoute = AboutMissionRouteImport.update({
  id: '/about/mission',
  path: '/about/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutKurnoolRoute = AboutKurnoolRouteImport.update({
  id: '/about/kurnool',
  path: '/about/kurnool',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIskconRoute = AboutIskconRouteImport.update({
  id: '/about/iskcon',
  path: '/about/iskcon',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutFounderRoute = AboutFounderRouteImport.update({
  id: '/about/founder',
  path: '/about/founder',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/connect': typeof ConnectRoute
  '/courses': typeof CoursesRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/goshala': typeof GoshalaRoute
  '/temple': typeof TempleRoute
  '/youth': typeof YouthRoute
  '/about/founder': typeof AboutFounderRoute
  '/about/iskcon': typeof AboutIskconRoute
  '/about/kurnool': typeof AboutKurnoolRoute
  '/about/mission': typeof AboutMissionRoute
  '/festival/$slug': typeof FestivalSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/connect': typeof ConnectRoute
  '/courses': typeof CoursesRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/goshala': typeof GoshalaRoute
  '/temple': typeof TempleRoute
  '/youth': typeof YouthRoute
  '/about/founder': typeof AboutFounderRoute
  '/about/iskcon': typeof AboutIskconRoute
  '/about/kurnool': typeof AboutKurnoolRoute
  '/about/mission': typeof AboutMissionRoute
  '/festival/$slug': typeof FestivalSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/connect': typeof ConnectRoute
  '/courses': typeof CoursesRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/goshala': typeof GoshalaRoute
  '/temple': typeof TempleRoute
  '/youth': typeof YouthRoute
  '/about/founder': typeof AboutFounderRoute
  '/about/iskcon': typeof AboutIskconRoute
  '/about/kurnool': typeof AboutKurnoolRoute
  '/about/mission': typeof AboutMissionRoute
  '/festival/$slug': typeof FestivalSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/connect'
    | '/courses'
    | '/donate'
    | '/gallery'
    | '/goshala'
    | '/temple'
    | '/youth'
    | '/about/founder'
    | '/about/iskcon'
    | '/about/kurnool'
    | '/about/mission'
    | '/festival/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/connect'
    | '/courses'
    | '/donate'
    | '/gallery'
    | '/goshala'
    | '/temple'
    | '/youth'
    | '/about/founder'
    | '/about/iskcon'
    | '/about/kurnool'
    | '/about/mission'
    | '/festival/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/connect'
    | '/courses'
    | '/donate'
    | '/gallery'
    | '/goshala'
    | '/temple'
    | '/youth'
    | '/about/founder'
    | '/about/iskcon'
    | '/about/kurnool'
    | '/about/mission'
    | '/festival/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ConnectRoute: typeof ConnectRoute
  CoursesRoute: typeof CoursesRoute
  DonateRoute: typeof DonateRoute
  GalleryRoute: typeof GalleryRoute
  GoshalaRoute: typeof GoshalaRoute
  TempleRoute: typeof TempleRoute
  YouthRoute: typeof YouthRoute
  AboutFounderRoute: typeof AboutFounderRoute
  AboutIskconRoute: typeof AboutIskconRoute
  AboutKurnoolRoute: typeof AboutKurnoolRoute
  AboutMissionRoute: typeof AboutMissionRoute
  FestivalSlugRoute: typeof FestivalSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youth': {
      id: '/youth'
      path: '/youth'
      fullPath: '/youth'
      preLoaderRoute: typeof YouthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temple': {
      id: '/temple'
      path: '/temple'
      fullPath: '/temple'
      preLoaderRoute: typeof TempleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goshala': {
      id: '/goshala'
      path: '/goshala'
      fullPath: '/goshala'
      preLoaderRoute: typeof GoshalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festival/$slug': {
      id: '/festival/$slug'
      path: '/festival/$slug'
      fullPath: '/festival/$slug'
      preLoaderRoute: typeof FestivalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/mission': {
      id: '/about/mission'
      path: '/about/mission'
      fullPath: '/about/mission'
      preLoaderRoute: typeof AboutMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/kurnool': {
      id: '/about/kurnool'
      path: '/about/kurnool'
      fullPath: '/about/kurnool'
      preLoaderRoute: typeof AboutKurnoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/iskcon': {
      id: '/about/iskcon'
      path: '/about/iskcon'
      fullPath: '/about/iskcon'
      preLoaderRoute: typeof AboutIskconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/founder': {
      id: '/about/founder'
      path: '/about/founder'
      fullPath: '/about/founder'
      preLoaderRoute: typeof AboutFounderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ConnectRoute: ConnectRoute,
  CoursesRoute: CoursesRoute,
  DonateRoute: DonateRoute,
  GalleryRoute: GalleryRoute,
  GoshalaRoute: GoshalaRoute,
  TempleRoute: TempleRoute,
  YouthRoute: YouthRoute,
  AboutFounderRoute: AboutFounderRoute,
  AboutIskconRoute: AboutIskconRoute,
  AboutKurnoolRoute: AboutKurnoolRoute,
  AboutMissionRoute: AboutMissionRoute,
  FestivalSlugRoute: FestivalSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
